export interface Departamento {
  name: string;
}

export interface Sector {
  name: string;
}

export interface Aliado {
  name: string;
}

export const Departamentos = (): Departamento[] => {
  const departamentos: Departamento[] = [
    { name: "Amazonas" },
    { name: "Antioquia" },
    { name: "Arauca" },
    { name: "Archipiélago de San Andrés, Providencia y Santa Catalina" },
    { name: "Atlántico" },
    { name: "Bogotá D.C" },
    { name: "Bolivar" },
    { name: "Boyacá" },
    { name: "Caldas" },
    { name: "Caquetá" },
    { name: "Casanare" },
    { name: "Cauca" },
    { name: "Cesar" },
    { name: "Chocó" },
    { name: "Córdoba" },
    { name: "Cundinamarca" },
    { name: "Guainía" },
    { name: "Guaviare" },
    { name: "Huila" },
    { name: "Guajira" },
    { name: "Magdalena" },
    { name: "Meta" },
    { name: "Nariño" },
    { name: "Norte de Santander" },
    { name: "Putumayo" },
    { name: "Quindío" },
    { name: "Risaralda" },
    { name: "Santander" },
    { name: "Sucre" },
    { name: "Tolima" },
    { name: "Valle del Cauca" },
    { name: "Vaupés" },
    { name: "Vichada" },
  ];

  return departamentos;
};

export const Aliados = (): Aliado[] => {
  const cargos: Aliado[] = [
    { name: "Cámara de Comercio Palmira" },
    { name: "El templo de la moda" },
    { name: "Gobernación del Valle (pendiente nombre alianza)" },
    { name: "Acodres capitulo Pacifico" },
    { name: "Procaña" },
    { name: "SIDOC (cliente modelo especializado)" },
    { name: "Cavassa Cali" },
    { name: "Câmara de Comercio Buga" },
    { name: "Valle Impacta" },
  ];
  return cargos;
};

export const Sectores = (): Sector[] => {
  const sectores: Sector[] = [
    { name: "Acabado de productos textiles." },
    { name: "Actividad de mezcla de combustibles." },
    { name: "Actividades de administración de fondos." },
    { name: "Actividades de aeropuertos, servicios de navegación aérea y" },
    { name: "Actividades de agencias de cobranza y oficinas de calificaci" },
    { name: "Actividades de agencias de empleo temporal." },
    { name: "Actividades de agencias de empleo." },
    { name: "Actividades de agencias de noticias." },
    { name: "Actividades de agentes y corredores de seguros" },
    { name: "Actividades de apoyo a la agricultura." },
    { name: "Actividades de apoyo a la ganadería." },
    { name: "Actividades de apoyo diagnóstico." },
    { name: "Actividades de apoyo para la extracción de petróleo y de gas" },
    { name: "Actividades de apoyo terapéutico." },
    { name: "Actividades de arquitectura e ingeniería y otras actividades" },
    { name: "Actividades de asistencia social sin alojamiento para person" },
    { name: "Actividades de asociaciones empresariales y de empleadores" },
    { name: "Actividades de asociaciones políticas." },
    { name: "Actividades de asociaciones profesionales" },
    { name: "Actividades de asociaciones religiosas." },
    { name: "Actividades de atención en instituciones para el cuidado de" },
    { name: "Actividades de atención residencial, para el cuidado de paci" },
    { name: "Actividades de bibliotecas y archivos." },
    { name: "Actividades de centros de llamadas (call center)." },
    { name: "Actividades de clubes deportivos." },
    { name: "Actividades de compra de cartera o factoring." },
    { name: "Actividades de consultaría de gestión." },
    { name: "Actividades de consultoría informática y actividades de admi" },
    { name: "Actividades de contabilidad, teneduría de libros, auditoría" },
    { name: "Actividades de defensa." },
    { name: "Actividades de desarrollo de sistemas informáticos (planific" },
    { name: "Actividades de distribución de películas cinematográficas, v" },
    { name: "Actividades de envase y empaque." },
    { name: "Actividades de espectáculos musicales en vivo." },
    { name: "Actividades de estaciones, vías y servicios complementarios" },
    { name: "Actividades de exhibición de películas cinematográficas y vi" },
    { name: "Actividades de fotografía." },
    { name: "Actividades de grabación de sonido y edición de música." },
    { name: "Actividades de hospitales y clínicas, con internación." },
    { name: "Actividades de impresión." },
    { name: "Actividades de ingenieria y otras actividades conexas de con" },
    { name: "Actividades de jardines botánicos, zoológicos y reservas nat" },
    { name: "Actividades de juegos de azar y apuestas." },
    { name: "Actividades de la práctica médica, sin internación." },
    { name: "Actividades de la práctica odontológica." },
    { name: "Actividades de las agencias de viaje." },
    { name: "Actividades de las casas de cambio." },
    { name: "Actividades de las compañías de financiamiento." },
    { name: "Actividades de las cooperativas financieras." },
    { name: "Actividades de las corporaciones financieras." },
    { name: "Actividades de los hogares individuales como empleadores de" },
    { name: "Actividades de los otros órganos de control." },
    { name: "Actividades de los profesionales de compra y venta de divisa" },
    { name: "Actividades de mensajería." },
    { name: "Actividades de operadores turísticos." },
    { name: "Actividades de organizaciones y entidades extraterritoriales" },
    { name: "Actividades de otras asociaciones n.c.p." },
    { name: "Actividades de otros servicios de comidas." },
    { name: "Actividades de paisajismo y servicios de mantenimiento conex" },
    { name: "Actividades de parques de atracciones y parques temáticos." },
    { name: "Actividades de planes de seguridad social de afiliación obli" },
    { name: "Actividades de posproducción de películas cinematográficas," },
    { name: "Actividades de producción de películas cinematográficas, vid" },
    { name: "Actividades de programación y transmisión de televisión." },
    { name: "Actividades de programación y transmisión en el servicio de" },
    { name: "Actividades de puertos y servicios complementarios para el t" },
    { name: "Actividades de saneamiento ambiental y otros servicios de ge" },
    { name: "Actividades de seguridad privada." },
    { name: "Actividades de servicios relacionados con la impresión." },
    { name: "Actividades de sindicatos de empleados." },
    { name: "Actividades de telecomunicación satelital." },
    { name: "Actividades de telecomunicaciones alámbricas." },
    { name: "Actividades de telecomunicaciones inalámbricas." },
    { name: "Actividades de zonas de camping y parques para vehículos rec" },
    { name: "Actividades ejecutivas de la administración pública." },
    { name: "Actividades especializadas de diseño." },
    { name: "Actividades financieras de fondos de empleados y otras forma" },
    { name: "Actividades inmobiliarias realizadas a cambio de una retribu" },
    { name: "Actividades inmobiliarias realizadas con bienes propios o ar" },
    { name: "Actividades jurídicas." },
    { name: "Actividades legislativas de la administración pública." },
    { name: "Actividades no diferenciadas de los hogares individuales com" },
    { name: "Actividades no diferenciadas de los hogares individuales com" },
    { name: "Actividades postales nacionales." },
    { name: "Actividades reguladoras y facilitadoras de la actividad econ" },
    { name: "Actividades teatrales." },
    { name: "Actividades veterinarias." },
    { name: "Actividades y funcionamiento de museos, conservación de edif" },
    { name: "Acuicultura de agua dulce." },
    { name: "Acuicultura marítima." },
    { name: "Administración de justicia." },
    { name: "Administración de mercados financieros." },
    { name: "Almacenamiento y depósito." },
    { name: "Alojamiento en apartahoteles." },
    { name: "Alojamiento en centros vacacionales." },
    { name: "Alojamiento en hoteles." },
    { name: "Alojamiento rural." },
    { name: "Alquiler de videos y discos." },
    { name: "Alquiler y arrendamiento de equipo recreativo y deportivo." },
    { name: "Alquiler y arrendamiento de otros efectos personales y enser" },
    { name: "Alquiler y arrendamiento de otros tipos de maquinaria, equip" },
    { name: "Alquiler y arrendamiento de vehículos automotores." },
    { name: "Arrendamiento de propiedad intelectual y productos similares" },
    { name: "Artes plásticas y visuales." },
    { name: "Aserrado, acepillado e impregnación de la madera." },
    { name: "Banco central." },
    { name: "Bancos comerciales." },
    { name: "Capitalización." },
    { name: "Captación, tratamiento y distribución de agua." },
    { name: "Caza ordinaria y mediante trampas y actividades de servicios" },
    { name: "Comercialización de energía eléctrica." },
    { name: "Comercio al por mayor a cambio de una retribución o por cont" },
    { name: "Comercio al por mayor de aparatos y equipo de uso doméstico." },
    { name: "Comercio al por mayor de bebidas y tabaco." },
    { name: "Comercio al por mayor de calzado." },
    { name: "Comercio al por mayor de combustibles sólidos, líquidos, gas" },
    { name: "Comercio al por mayor de computadores, equipo periférico y p" },
    { name: "Comercio al por mayor de desperdicios, desechos y chatarra." },
    { name: "Comercio al por mayor de equipo, partes y piezas electrónico" },
    { name: "Comercio al por mayor de maquinaria y equipo agropecuarios." },
    { name: "Comercio al por mayor de materiales de construcción, artícul" },
    { name: "Comercio al por mayor de materias primas agropecuarias; anim" },
    { name: "Comercio al por mayor de metales y productos metalíferos." },
    { name: "Comercio al por mayor de otros productos n.c.p." },
    { name: "Comercio al por mayor de otros utensilios domésticos n.c.p." },
    { name: "Comercio al por mayor de prendas de vestir." },
    { name: "Comercio al por mayor de productos alimenticios." },
    { name: "Comercio al por mayor de productos farmacéuticos, medicinale" },
    { name: "Comercio al por mayor de productos químicos básicos, cauchos" },
    { name: "Comercio al por mayor de productos textiles, productos confe" },
    { name: "Comercio al por mayor no especializado." },
    { name: "Comercio al por menor de alimentos, bebidas y tabaco, en pue" },
    { name: "Comercio al por menor de artículos de ferretería, pinturas y" },
    { name: "Comercio al por menor de artículos de segunda mano." },
    { name: "Comercio al por menor de artículos deportivos, en establecim" },
    { name: "Comercio al por menor de artículos y utensilios de uso domés" },
    { name: "Comercio al por menor de bebidas y productos del tabaco, en" },
    { name: "Comercio al por menor de carnes (incluye aves de corral), pr" },
    { name: "Comercio al por menor de combustible para automotores." },
    { name: "Comercio al por menor de computadores, equipos periféricos," },
    { name: "Comercio al por menor de electrodomésticos y gasodomésticos" },
    { name: "Comercio al por menor de equipos y aparatos de sonido y de v" },
    { name: "Comercio al por menor de leche, productos lácteos y huevos," },
    { name: "Comercio al por menor de libros, periódicos, materiales y ar" },
    { name: "Comercio al por menor de lubricantes (aceites, grasas), adit" },
    { name: "Comercio al por menor de otros artículos culturales y de ent" },
    { name: "Comercio al por menor de otros artículos domésticos en estab" },
    { name: "Comercio al por menor de otros productos alimenticios n.c.p." },
    { name: "Comercio al por menor de otros productos en puestos de venta" },
    { name: "Comercio al por menor de prendas de vestir y sus accesorios" },
    { name: "Comercio al por menor de productos agrícolas para el consumo" },
    { name: "Comercio al por menor de productos farmacéuticos y medicinal" },
    { name: "Comercio al por menor de productos textiles en establecimien" },
    { name: "Comercio al por menor de productos textiles, prendas de vest" },
    { name: "Comercio al por menor de tapices, alfombras y cubrimientos p" },
    { name: "Comercio al por menor de todo tipo de calzado y artículos de" },
    { name: "Comercio al por menor en establecimientos no especializados" },
    { name: "Comercio al por menor en establecimientos no especializados," },
    { name: "Comercio al por menor realizado a través de casas de venta o" },
    { name: "Comercio al por menor realizado a través de internet." },
    { name: "Comercio de motocicletas y de sus partes, piezas y accesorio" },
    { name: "Comercio de partes, piezas (autopartes) y accesorios (lujos)" },
    { name: "Comercio de vehículos automotores nuevos." },
    { name: "Comercio de vehículos automotores usados." },
    { name: "Confección de artículos con materiales textiles, excepto pre" },
    { name: "Confección de prendas de vestir, excepto prendas de piel." },
    { name: "Construcción de barcos y de estructuras flotantes." },
    { name: "Construcción de carreteras y vías de ferrocarril." },
    { name: "Construcción de edificios no residenciales." },
    { name: "Construcción de edificios residenciales." },
    { name: "Construcción de embarcaciones de recreo y deporte." },
    { name: "Construcción de otras obras de ingeniería civil." },
    { name: "Construcción de proyectos de servicio público." },
    { name: "Corretaje de valores y de contratos de productos básicos." },
    { name: "Corte, tallado y acabado de la piedra." },
    { name: "Creación audiovisual." },
    { name: "Creación literaria." },
    { name: "Creación musical." },
    { name: "Creación teatral." },
    { name: "Cría de aves de corral." },
    { name: "Cría de caballos y otros equinos." },
    { name: "Cría de ganado bovino y bufalino." },
    { name: "Cría de ganado porcino." },
    { name: "Cría de otros animales n.c.p." },
    { name: "Cría de ovejas y cabras." },
    { name: "Cultivo de arroz." },
    { name: "Cultivo de café." },
    { name: "Cultivo de caña de azúcar." },
    { name: "Cultivo de cereales (excepto arroz), legumbres y semillas ol" },
    { name: "Cultivo de especias y de plantas aromáticas y medicinales." },
    { name: "Cultivo de flor de corte." },
    { name: "Cultivo de frutas tropicales y subtropicales." },
    { name: "Cultivo de hortalizas, raíces y tubérculos." },
    { name: "Cultivo de palma para aceite (palma africana) y otros frutos" },
    { name: "Cultivo de plantas con las que se preparan bebidas." },
    { name: "Cultivo de plantas textiles." },
    { name: "Cultivo de plátano y banano." },
    { name: "Cultivo de tabaco." },
    { name: "Curtido y recurtido de cueros; recurtido y teñido de pieles." },
    { name: "Demolición." },
    { name: "Descafeinado, tostión y molienda del café." },
    { name: "Destilación, rectificación y mezcla de bebidas alcohólicas." },
    { name: "Distribución de energía eléctrica." },
    { name: "Edición de directorios y listas de correo." },
    { name: "Edición de libros." },
    { name: "Edición de periódicos, revistas y otras publicaciones periód" },
    { name: "Edición de programas de informática (software)." },
    { name: "Educación básica primaria." },
    { name: "Educación básica secundaria." },
    { name: "Educación de instituciones universitarias o de escuelas tecn" },
    { name: "Educación de la primera infancia." },
    { name: "Educación de universidades." },
    { name: "Educación media académica." },
    { name: "Educación media técnica y de formación laboral." },
    { name: "Educación preescolar." },
    { name: "Educación técnica profesional." },
    { name: "Educación tecnológica." },
    { name: "Elaboración de aceites y grasas de origen vegetal y animal." },
    { name: "Elaboración de alimentos preparados para animales." },
    { name: "Elaboración de almidones y productos derivados del almidón." },
    { name: "Elaboración de bebidas fermentadas no destiladas." },
    { name: "Elaboración de bebidas no alcohólicas, producción de aguas m" },
    { name: "Elaboración de cacao, chocolate y productos de confitería." },
    { name: "Elaboración de comidas y platos preparados." },
    { name: "Elaboración de macarrones, fideos, alcuzcuz y productos fari" },
    { name: "Elaboración de otros productos alimenticios n.c.p." },
    { name: "Elaboración de panela." },
    { name: "Elaboración de productos de molinería." },
    { name: "Elaboración de productos de panadería." },
    { name: "Elaboración de productos de tabaco." },
    { name: "Elaboración de productos lácteos." },
    { name: "Elaboración y refinación de azúcar." },
    { name: "Ensayos y análisis técnicos." },
    { name: "Enseñanza cultural." },
    { name: "Enseñanza deportiva y recreativa." },
    { name: "Establecimientos que combinan diferentes niveles de educació" },
    { name: "Estudios de mercado y realización de encuestas de opinión pú" },
    { name: "Evacuación y tratamiento de aguas residuales." },
    { name: "Expendio a la mesa de comidas preparadas." },
    { name: "Expendio de bebidas alcohólicas para el consumo dentro del e" },
    { name: "Expendio de comidas preparadas en cafeterías." },
    { name: "Expendio por autoservicio de comidas preparadas." },
    { name: "Explotación mixta (agrícola y pecuaria)." },
    { name: "Extracción de arcillas de uso industrial, caliza, caolín y b" },
    { name: "Extracción de carbón lignito." },
    { name: "Extracción de esmeraldas, piedras preciosas y semipreciosas." },
    { name: "Extracción de gas natural." },
    { name: "Extracción de halita (sal)." },
    { name: "Extracción de hulla (carbón de piedra)." },
    { name: "Extracción de minerales de hierro." },
    { name: "Extracción de minerales de níquel." },
    { name: "Extracción de minerales de uranio y de torio." },
    { name: "Extracción de minerales para la fabricación de abonos y prod" },
    { name: "Extracción de oro y otros metales preciosos." },
    { name: "Extracción de otros minerales metalíferos no ferrosos n.c.p." },
    { name: "Extracción de otros minerales no metálicos n.c.p." },
    { name: "Extracción de petróleo crudo." },
    { name: "Extracción de piedra, arena, arcillas comunes, yeso y anhidr" },
    { name: "Fabricación de abonos y compuestos inorgánicos nitrogenados." },
    { name: "Fabricación de aeronaves, naves espaciales y de maquinaria c" },
    { name: "Fabricación de aparatos de distribución y control de la ener" },
    { name: "Fabricación de aparatos de uso doméstico." },
    { name: "Fabricación de aparatos electrónicos de consumo." },
    { name: "Fabricación de armas y municiones." },
    { name: "Fabricación de artículos de cuchillería, herramientas de man" },
    { name: "Fabricación de artículos de hormigón, cemento y yeso." },
    { name: "Fabricación de artículos de piel." },
    { name: "Fabricación de artículos de plástico n.c.p." },
    { name: "Fabricación de artículos de punto y ganchillo." },
    { name: "Fabricación de artículos de viaje, bolsos de mano y artículo" },
    { name: "Fabricación de artículos de viaje, bolsos de mano y artículo" },
    { name: "Fabricación de artículos y equipo para la práctica del depor" },
    { name: "Fabricación de bicicletas y de sillas de ruedas para persona" },
    { name: "Fabricación de calzado de cuero y piel, con cualquier tipo d" },
    { name: "Fabricación de carrocerías para vehículos automotores; fabri" },
    { name: "Fabricación de caucho sintético en formas primarias." },
    { name: "Fabricación de cemento, cal y yeso." },
    { name: "Fabricación de cojinetes, engranajes, trenes de engranajes y" },
    { name: "Fabricación de colchones y somieres." },
    { name: "Fabricación de componentes y tableros electrónicos." },
    { name: "Fabricación de computadoras y de equipo periférico." },
    { name: "Fabricación de cuerdas, cordeles, cables, bramantes y redes." },
    { name: "Fabricación de dispositivos de cableado." },
    { name: "Fabricación de equipo de elevación y manipulación." },
    { name: "Fabricación de equipo de irradiación y equipo electrónico de" },
    { name: "Fabricación de equipo de medición, prueba, navegación y cont" },
    { name: "Fabricación de equipos de comunicación." },
    { name: "Fabricación de equipos eléctricos de iluminación." },
    { name: "Fabricación de fibras sintéticas y artificiales." },
    { name: "Fabricación de formas básicas de caucho y otros productos de" },
    { name: "Fabricación de formas básicas de plástico." },
    { name: "Fabricación de generadores de vapor, excepto calderas de agu" },
    { name: "Fabricación de herramientas manuales con motor." },
    { name: "Fabricación de hilos y cables eléctricos y de fibra óptica." },
    { name: "Fabricación de hojas de madera para enchapado; fabricación d" },
    { name: "Fabricación de hornos, hogares y quemadores industriales." },
    { name: "Fabricación de instrumentos musicales." },
    { name: "Fabricación de instrumentos ópticos y equipo fotográfico." },
    { name: "Fabricación de jabones y detergentes, preparados para limpia" },
    { name: "Fabricación de joyas, bisutería y artículos conexos." },
    { name: "Fabricación de juegos, juguetes y rompecabezas." },
    { name: "Fabricación de llantas y neumáticos de caucho" },
    { name: "Fabricación de locomotoras y de material rodante para ferroc" },
    { name: "Fabricación de maquinaria agropecuaria y forestal." },
    { name: "Fabricación de maquinaria para explotación de minas y canter" },
    { name: "Fabricación de maquinaria para la elaboración de alimentos," },
    { name: "Fabricación de maquinaria para la elaboración de productos t" },
    { name: "Fabricación de maquinaria para la metalurgia." },
    { name: "Fabricación de maquinaria y equipo de oficina (excepto compu" },
    { name: "Fabricación de máquinas formadoras de metal y de máquinas he" },
    { name: "Fabricación de materiales de arcilla para la construcción." },
    { name: "Fabricación de medios magnéticos y ópticos para almacenamien" },
    { name: "Fabricación de motocicletas." },
    { name: "Fabricación de motores, generadores y transformadores eléctr" },
    { name: "Fabricación de motores, turbinas, y partes para motores de c" },
    { name: "Fabricación de muebles." },
    { name: "Fabricación de otras bombas, compresores, grifos y válvulas." },
    { name: "Fabricación de otros artículos de papel y cartón." },
    { name: "Fabricación de otros artículos textiles n.c.p." },
    { name: "Fabricación de otros productos de cerámica y porcelana." },
    { name: "Fabricación de otros productos de madera; fabricación de art" },
    { name: "Fabricación de otros productos elaborados de metal n.c.p." },
    { name: "Fabricación de otros productos minerales no metálicos n.c.p." },
    { name: "Fabricación de otros productos químicos n.c.p." },
    { name: "Fabricación de otros tipos de calzado, excepto calzado de cu" },
    { name: "Fabricación de otros tipos de equipo de transporte n.c.p." },
    { name: "Fabricación de otros tipos de equipo eléctrico n.c.p." },
    { name: "Fabricación de otros tipos de maquinaria y equipo de uso esp" },
    { name: "Fabricación de otros tipos de maquinaria y equipo de uso gen" },
    { name: "Fabricación de papel y cartón ondulado (corrugado); fabricac" },
    { name: "Fabricación de partes del calzado." },
    { name: "Fabricación de partes y piezas de madera, de carpintería y e" },
    { name: "Fabricación de partes, piezas (autopartes) y accesorios (luj" },
    { name: "Fabricación de pilas, baterías y acumuladores eléctricos." },
    { name: "Fabricación de pinturas, barnices y revestimientos similares" },
    { name: "Fabricación de plaguicidas y otros productos químicos de uso" },
    { name: "Fabricación de plásticos en formas primarias." },
    { name: "Fabricación de productos de hornos de coque." },
    { name: "Fabricación de productos de la refinación del petróleo." },
    { name: "Fabricación de productos farmacéuticos, sustancias químicas" },
    { name: "Fabricación de productos metálicos para uso estructural." },
    { name: "Fabricación de productos refractarios." },
    { name: "Fabricación de pulpas (pastas) celulósicas; papel y cartón." },
    { name: "Fabricación de recipientes de madera." },
    { name: "Fabricación de relojes." },
    { name: "Fabricación de sustancias y productos químicos básicos." },
    { name: "Fabricación de tanques, depósitos y recipientes de metal, ex" },
    { name: "Fabricación de tapetes y alfombras para pisos." },
    { name: "Fabricación de tejidos de punto y ganchillo." },
    { name: "Fabricación de vehículos automotores y sus motores." },
    { name: "Fabricación de vehículos militares de combate." },
    { name: "Fabricación de vidrio y productos de vidrio." },
    { name: "Fideicomisos, fondos y entidades financieras similares." },
    { name: "Fondos de cesantías." },
    { name: "Forja, prensado, estampado y laminado de metal; pulvimetalur" },
    { name: "Formación académica no formal." },
    { name: "Fundición de hierro y de acero." },
    { name: "Fundición de metales no ferrosos." },
    { name: "Generación de energía eléctrica." },
    { name: "Gestión de instalaciones deportivas." },
    { name: "Industrias básicas de metales preciosos." },
    { name: "Industrias básicas de otros metales no ferrosos." },
    { name: "Instalación especializada de maquinaria y equipo industrial." },
    { name: "Instalaciones de fontanería, calefacción y aire acondicionad" },
    { name: "Instalaciones eléctricas." },
    { name: "Instituciones especiales oficiales." },
    { name: "Investigaciones y desarrollo experimental en el campo de las" },
    { name: "Investigaciones y desarrollo experimental en el campo de las" },
    { name: "Lavado y limpieza, incluso la limpieza en seco, de productos" },
    { name: "Leasing financiero (arrendamiento financiero)." },
    { name: "Limpieza general interior de edificios." },
    { name: "Manipulación de carga." },
    { name: "Mantenimiento y reparación de aparatos electrónicos de consu" },
    { name: "Mantenimiento y reparación de aparatos y equipos domésticos" },
    { name: "Mantenimiento y reparación de computadores y de equipo perif" },
    { name: "Mantenimiento y reparación de equipos de comunicación." },
    { name: "Mantenimiento y reparación de otros efectos personales y ens" },
    { name: "Mantenimiento y reparación de vehículos automotores." },
    { name: "Mantenimiento y reparación especializado de equipo eléctrico" },
    { name: "Mantenimiento y reparación especializado de maquinaria y equ" },
    { name: "Mantenimiento y reparación especializado de productos elabor" },
    { name: "Orden público y actividades de seguridad." },
    { name: "Organización de convenciones y eventos comerciales." },
    { name: "Otras actividades auxiliares de las actividades de servicios" },
    { name: "Otras actividades complementarias al transporte." },
    { name: "Otras actividades de asistencia social sin alojamiento." },
    { name: "Otras actividades de atención en instituciones con alojamien" },
    { name: "Otras actividades de distribución de fondos." },
    { name: "Otras actividades de espectáculos en vivo." },
    { name: "Otras actividades de limpieza de edificios e instalaciones i" },
    { name: "Otras actividades de servicio de apoyo a las empresas n.c.p." },
    { name: "Otras actividades de servicio de información n.c.p." },
    { name: "Otras actividades de servicio financiero, excepto las de seg" },
    { name: "Otras actividades de servicios personales n.c.p." },
    { name: "Otras actividades de suministro de recurso humano." },
    { name: "Otras actividades de tecnologías de información y actividade" },
    { name: "Otras actividades de telecomunicaciones." },
    { name: "Otras actividades deportivas." },
    { name: "Otras actividades especializadas para la construcción de edi" },
    { name: "Otras actividades profesionales, científicas y técnicas n.c." },
    { name: "Otras actividades recreativas y de esparcimiento n.c.p." },
    { name: "Otras actividades relacionadas con el mercado de valores." },
    { name: "Otras industrias manufactureras n.c.p." },
    { name: "Otras instalaciones especializadas." },
    { name: "Otros cultivos permanentes n.c.p." },
    { name: "Otros cultivos transitorios n.c.p." },
    { name: "Otros derivados del café." },
    { name: "Otros servicios de reserva y actividades relacionadas." },
    { name: "Otros tipos de alojamiento n.c.p." },
    { name: "Otros tipos de alojamientos para visitantes." },
    { name: "Otros tipos de comercio al por menor no realizado en estable" },
    { name: "Otros tipos de educación n.c.p." },
    { name: "Otros tipos de expendio de comidas preparadas n.c.p." },
    { name: "Otros trabajos de edición." },
    { name: "Peluquería y otros tratamientos de belleza." },
    { name: "Pesca de agua dulce." },
    { name: "Pesca marítima." },
    { name: "Pompas fúnebres y actividades relacionadas." },
    { name: "Portales web." },
    { name: "Preparación del terreno." },
    { name: "Preparación e hilatura de fibras textiles." },
    { name: "Procesamiento de datos, alojamiento (hosting) y actividades" },
    { name: "Procesamiento y conservación de frutas, legumbres, hortaliza" },
    { name: "Producción de copias a partir de grabaciones originales." },
    { name: "Producción de gas; distribución de combustibles gaseosos por" },
    { name: "Producción de malta, elaboración de cervezas y otras bebidas" },
    { name: "Publicidad." },
    { name: "Reaseguros." },
    { name: "Recolección de desechos no peligrosos." },
    { name: "Recuperación de materiales." },
    { name: "Reencauche de llantas usadas" },
    { name: "Régimen de ahorro individual (rai)." },
    { name: "Régimen de prima media con prestación definida (rpm)." },
    { name: "Regulación de las actividades de organismos que prestan serv" },
    { name: "Relaciones exteriores." },
    { name: "Reparación de calzado y artículos de cuero." },
    { name: "Reparación de muebles y accesorios para el hogar." },
    { name: "Seguros de vida." },
    { name: "Seguros generales." },
    { name: "Servicio por horas" },
    { name: "Servicios de apoyo a la silvicultura." },
    { name: "Servicios de seguros sociales de riesgos profesionales." },
    { name: "Servicios de seguros sociales de salud." },
    { name: "Silvicultura y otras actividades forestales." },
    { name: "Suministro de vapor y aire acondicionado." },
    { name: "Tejeduría de productos textiles." },
    { name: "Terminación y acabado de edificios y obras de ingeniería civ" },
    { name: "Transmisión de energía eléctrica." },
    { name: "Transporte aéreo internacional de carga." },
    { name: "Transporte aéreo internacional de pasajeros." },
    { name: "Transporte aéreo nacional de carga." },
    { name: "Transporte aéreo nacional de pasajeros." },
    { name: "Transporte de carga marítimo y de cabotaje." },
    { name: "Transporte de carga por carretera." },
    { name: "Transporte de pasajeros marítimo y de cabotaje." },
    { name: "Transporte de pasajeros." },
    { name: "Transporte férreo de carga." },
    { name: "Transporte férreo de pasajeros." },
    { name: "Transporte fluvial de carga." },
    { name: "Transporte fluvial de pasajeros." },
    { name: "Transporte mixto." },
    { name: "Transporte por tuberías." },
    { name: "Tratamiento de semillas para propagación." },
    { name: "Tratamiento y disposición de desechos no peligrosos." },
    { name: "Tratamiento y disposición de desechos peligrosos." },
    { name: "Tratamiento y revestimiento de metales; mecanizado." },
    { name: "Trilla de café." },
  ];

  return sectores;
};
