export const Rutas = {
  HOME: "/home",
  TERM_CONDICIONES: "/home/terminos-condiciones",
  DATOS_REGISTRO: "/home/datos-registro",
  TALENTO_HUMANO: "/home/talento-humano",
  TECNOLOGIA_TRANSFORMACION_DIGITAL: "/home/tecnologia-transformacion-digital",
  MERCADO: "/home/mercados",
  FINANCIERO: "/home/financiera",
  LEGAL: "/home/legal",
  MODELO_OPERATIVO: "/home/modelo-operativo",
  AMBIENTAL: "/home/ambiental",
  RESULTADOS: "/home/resultados-autodiagnostico",
  DATOS_REGISTRO_TALLERES: "/talleres/datos-registro-talleres",
  REGISTRO_TALLERES_GRACIAS: "/talleres/thank-you-talleres",
};